vich_uploader:
    db_driver: orm
    mappings:
        category_image:
            uri_prefix: /images/category
            upload_destination: '%kernel.project_dir%/public/images/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        projet_une:
            uri_prefix: /images/projet
            upload_destination: '%kernel.project_dir%/public/images/projet'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        projet_image1:
            uri_prefix: /images/projet
            upload_destination: '%kernel.project_dir%/public/images/projet'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        projet_image2:
            uri_prefix: /images/projet
            upload_destination: '%kernel.project_dir%/public/images/projet'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        projet_image3:
            uri_prefix: /images/projet
            upload_destination: '%kernel.project_dir%/public/images/projet'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        projet_image4:
            uri_prefix: /images/projet
            upload_destination: '%kernel.project_dir%/public/images/projet'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        projet_image5:
            uri_prefix: /images/projet
            upload_destination: '%kernel.project_dir%/public/images/projet'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        article_image:
            uri_prefix: /images/blog
            upload_destination: '%kernel.project_dir%/public/images/blog'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer